language: go
go:
 - 1.8.1
install:
 - cd $GOPATH
 - go get github.com/hashicorp/terraform
 - go get github.com/JamesClonk/vultr
before_script:
 - cd src/github.com/hashicorp/terraform
 - git checkout v0.8.8
 - rm -rf src/github.com/hashicorp/terraform/builtin/providers
 - pwd
